version: 0.2

phases:
  install:
    commands:
      - echo apt-get update -y
      - echo apt-get install -y apache2
      - echo apt-get install -y php7.0 php7.0-* libapache2-mod-php7.0 

files:
   - source: /
     destination: /var/www/html
   - source: /var/www/html/index.html
     destination: /tmp
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: root
     group: www-data
     mode: 755
     type:
       - file

